<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.SfKanban.WPF" Version="*" />
    <PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="*" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="*" />
    <PackageReference Include="Syncfusion.Themes.Material3Light.WPF" Version="*" />
  </ItemGroup>

</Project>
